
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class AbilityView : Luban.BeanBase
{
    public AbilityView(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AnimState = _buf.ReadString();
        AnimLayer = _buf.ReadInt();
    }

    public static AbilityView DeserializeAbilityView(ByteBuf _buf)
    {
        return new AbilityView(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// anim_state
    /// </summary>
    public readonly string AnimState;
    /// <summary>
    /// anim_layer
    /// </summary>
    public readonly int AnimLayer;
   
    public const int __ID__ = 1953588943;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "animState:" + AnimState + ","
        + "animLayer:" + AnimLayer + ","
        + "}";
    }
}
}

