
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class Cosmetic : Luban.BeanBase
{
    public Cosmetic(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Code = _buf.ReadString();
        SlotId = _buf.ReadInt();
        Name = _buf.ReadString();
        Tier = _buf.ReadInt();
        Purchasable = _buf.ReadBool();
        IsDefault = _buf.ReadBool();
        AssetKind = _buf.ReadString();
        AssetKey = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Prices = new System.Collections.Generic.List<Price>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Price _e0;  _e0 = global::LOP.MasterData.Price.DeserializePrice(_buf); Prices.Add(_e0);}}
    }

    public static Cosmetic DeserializeCosmetic(ByteBuf _buf)
    {
        return new Cosmetic(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// slot_id
    /// </summary>
    public readonly int SlotId;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// tier
    /// </summary>
    public readonly int Tier;
    /// <summary>
    /// purchasable
    /// </summary>
    public readonly bool Purchasable;
    /// <summary>
    /// is_default
    /// </summary>
    public readonly bool IsDefault;
    /// <summary>
    /// asset_kind
    /// </summary>
    public readonly string AssetKind;
    /// <summary>
    /// asset_key
    /// </summary>
    public readonly string AssetKey;
    /// <summary>
    /// prices
    /// </summary>
    public readonly System.Collections.Generic.List<Price> Prices;
   
    public const int __ID__ = -365991185;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Prices) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "slotId:" + SlotId + ","
        + "name:" + Name + ","
        + "tier:" + Tier + ","
        + "purchasable:" + Purchasable + ","
        + "isDefault:" + IsDefault + ","
        + "assetKind:" + AssetKind + ","
        + "assetKey:" + AssetKey + ","
        + "prices:" + Luban.StringUtil.CollectionToString(Prices) + ","
        + "}";
    }
}
}

