
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class CosmeticSlot : Luban.BeanBase
{
    public CosmeticSlot(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Code = _buf.ReadString();
        Name = _buf.ReadString();
        DisplayOrder = _buf.ReadInt();
        DefaultCosmeticId = _buf.ReadInt();
    }

    public static CosmeticSlot DeserializeCosmeticSlot(ByteBuf _buf)
    {
        return new CosmeticSlot(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// display_order
    /// </summary>
    public readonly int DisplayOrder;
    /// <summary>
    /// default_cosmetic_id
    /// </summary>
    public readonly int DefaultCosmeticId;
   
    public const int __ID__ = 498710925;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "name:" + Name + ","
        + "displayOrder:" + DisplayOrder + ","
        + "defaultCosmeticId:" + DefaultCosmeticId + ","
        + "}";
    }
}
}

