
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class Currency : Luban.BeanBase
{
    public Currency(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Code = _buf.ReadString();
        Name = _buf.ReadString();
        Type = _buf.ReadString();
        MaxBalance = _buf.ReadLong();
    }

    public static Currency DeserializeCurrency(ByteBuf _buf)
    {
        return new Currency(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// type
    /// </summary>
    public readonly string Type;
    /// <summary>
    /// max_balance
    /// </summary>
    public readonly long MaxBalance;
   
    public const int __ID__ = 640046129;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "code:" + Code + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "maxBalance:" + MaxBalance + ","
        + "}";
    }
}
}

