
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// 가격 한 줄
/// </summary>
public sealed partial class Price : Luban.BeanBase
{
    public Price(ByteBuf _buf) 
    {
        CurrencyId = _buf.ReadInt();
        Amount = _buf.ReadLong();
    }

    public static Price DeserializePrice(ByteBuf _buf)
    {
        return new Price(_buf);
    }

    public readonly int CurrencyId;
    public readonly long Amount;
   
    public const int __ID__ = 77381929;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "currencyId:" + CurrencyId + ","
        + "amount:" + Amount + ","
        + "}";
    }
}
}

