
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class RankDivision : Luban.BeanBase
{
    public RankDivision(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        TierCode = _buf.ReadString();
        TierName = _buf.ReadString();
        Division = _buf.ReadInt();
        MmrMin = _buf.ReadInt();
        DecayBankPerGame = _buf.ReadInt();
        DecayBankMax = _buf.ReadInt();
        DecayLpPerDay = _buf.ReadInt();
    }

    public static RankDivision DeserializeRankDivision(ByteBuf _buf)
    {
        return new RankDivision(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// tier_code
    /// </summary>
    public readonly string TierCode;
    /// <summary>
    /// tier_name
    /// </summary>
    public readonly string TierName;
    /// <summary>
    /// division
    /// </summary>
    public readonly int Division;
    /// <summary>
    /// mmr_min
    /// </summary>
    public readonly int MmrMin;
    /// <summary>
    /// decay_bank_per_game
    /// </summary>
    public readonly int DecayBankPerGame;
    /// <summary>
    /// decay_bank_max
    /// </summary>
    public readonly int DecayBankMax;
    /// <summary>
    /// decay_lp_per_day
    /// </summary>
    public readonly int DecayLpPerDay;
   
    public const int __ID__ = -347125479;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "tierCode:" + TierCode + ","
        + "tierName:" + TierName + ","
        + "division:" + Division + ","
        + "mmrMin:" + MmrMin + ","
        + "decayBankPerGame:" + DecayBankPerGame + ","
        + "decayBankMax:" + DecayBankMax + ","
        + "decayLpPerDay:" + DecayLpPerDay + ","
        + "}";
    }
}
}

