
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// 사유별 일일 상한
/// </summary>
public sealed partial class ReasonCap : Luban.BeanBase
{
    public ReasonCap(ByteBuf _buf) 
    {
        Reason = _buf.ReadString();
        CurrencyId = _buf.ReadInt();
        Amount = _buf.ReadLong();
    }

    public static ReasonCap DeserializeReasonCap(ByteBuf _buf)
    {
        return new ReasonCap(_buf);
    }

    public readonly string Reason;
    public readonly int CurrencyId;
    public readonly long Amount;
   
    public const int __ID__ = 1334525646;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "reason:" + Reason + ","
        + "currencyId:" + CurrencyId + ","
        + "amount:" + Amount + ","
        + "}";
    }
}
}

