
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class SkinAsset : Luban.BeanBase
{
    public SkinAsset(ByteBuf _buf) 
    {
        Code = _buf.ReadString();
        SkinCode = _buf.ReadString();
        ModelPath = _buf.ReadString();
    }

    public static SkinAsset DeserializeSkinAsset(ByteBuf _buf)
    {
        return new SkinAsset(_buf);
    }

    /// <summary>
    /// code
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// skin_code
    /// </summary>
    public readonly string SkinCode;
    /// <summary>
    /// model_path
    /// </summary>
    public readonly string ModelPath;
   
    public const int __ID__ = -281339053;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "code:" + Code + ","
        + "skinCode:" + SkinCode + ","
        + "modelPath:" + ModelPath + ","
        + "}";
    }
}
}

