
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
public sealed partial class StatusEffectView : Luban.BeanBase
{
    public StatusEffectView(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        VfxAddress = _buf.ReadString();
    }

    public static StatusEffectView DeserializeStatusEffectView(ByteBuf _buf)
    {
        return new StatusEffectView(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// vfx_address
    /// </summary>
    public readonly string VfxAddress;
   
    public const int __ID__ = -970694264;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "vfxAddress:" + VfxAddress + ","
        + "}";
    }
}
}

