
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace LOP.MasterData
{
public partial class Tables
{
    /// <summary>
    /// Character
    /// </summary>
    public TbCharacter TbCharacter {get; }
    /// <summary>
    /// Skin
    /// </summary>
    public TbSkin TbSkin {get; }
    /// <summary>
    /// SkinAsset
    /// </summary>
    public TbSkinAsset TbSkinAsset {get; }
    /// <summary>
    /// Item
    /// </summary>
    public TbItem TbItem {get; }
    /// <summary>
    /// StatusEffect
    /// </summary>
    public TbStatusEffect TbStatusEffect {get; }
    /// <summary>
    /// Ability
    /// </summary>
    public TbAbility TbAbility {get; }
    /// <summary>
    /// CharacterLoadout
    /// </summary>
    public TbCharacterLoadout TbCharacterLoadout {get; }
    /// <summary>
    /// AbilityView
    /// </summary>
    public TbAbilityView TbAbilityView {get; }
    /// <summary>
    /// StatusEffectView
    /// </summary>
    public TbStatusEffectView TbStatusEffectView {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbCharacter = new TbCharacter(loader("tbcharacter"));
        TbSkin = new TbSkin(loader("tbskin"));
        TbSkinAsset = new TbSkinAsset(loader("tbskinasset"));
        TbItem = new TbItem(loader("tbitem"));
        TbStatusEffect = new TbStatusEffect(loader("tbstatuseffect"));
        TbAbility = new TbAbility(loader("tbability"));
        TbCharacterLoadout = new TbCharacterLoadout(loader("tbcharacterloadout"));
        TbAbilityView = new TbAbilityView(loader("tbabilityview"));
        TbStatusEffectView = new TbStatusEffectView(loader("tbstatuseffectview"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCharacter.ResolveRef(this);
        TbSkin.ResolveRef(this);
        TbSkinAsset.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbStatusEffect.ResolveRef(this);
        TbAbility.ResolveRef(this);
        TbCharacterLoadout.ResolveRef(this);
        TbAbilityView.ResolveRef(this);
        TbStatusEffectView.ResolveRef(this);
    }
}

}
