
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// AbilityView
/// </summary>
public partial class TbAbilityView
{
    private readonly System.Collections.Generic.Dictionary<int, AbilityView> _dataMap;
    private readonly System.Collections.Generic.List<AbilityView> _dataList;
    
    public TbAbilityView(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, AbilityView>(n);
        _dataList = new System.Collections.Generic.List<AbilityView>(n);
        for(int i = n ; i > 0 ; --i)
        {
            AbilityView _v;
            _v = global::LOP.MasterData.AbilityView.DeserializeAbilityView(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, AbilityView> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<AbilityView> DataList => _dataList;

    public AbilityView GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public AbilityView Get(int key) => _dataMap[key];
    public AbilityView this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

