
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// 꾸밈 품목
/// </summary>
public partial class TbCosmetic
{
    private readonly System.Collections.Generic.Dictionary<int, Cosmetic> _dataMap;
    private readonly System.Collections.Generic.List<Cosmetic> _dataList;
    
    public TbCosmetic(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Cosmetic>(n);
        _dataList = new System.Collections.Generic.List<Cosmetic>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Cosmetic _v;
            _v = global::LOP.MasterData.Cosmetic.DeserializeCosmetic(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Cosmetic> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Cosmetic> DataList => _dataList;

    public Cosmetic GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Cosmetic Get(int key) => _dataMap[key];
    public Cosmetic this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

