
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// 꾸밈 슬롯
/// </summary>
public partial class TbCosmeticSlot
{
    private readonly System.Collections.Generic.Dictionary<int, CosmeticSlot> _dataMap;
    private readonly System.Collections.Generic.List<CosmeticSlot> _dataList;
    
    public TbCosmeticSlot(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, CosmeticSlot>(n);
        _dataList = new System.Collections.Generic.List<CosmeticSlot>(n);
        for(int i = n ; i > 0 ; --i)
        {
            CosmeticSlot _v;
            _v = global::LOP.MasterData.CosmeticSlot.DeserializeCosmeticSlot(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, CosmeticSlot> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<CosmeticSlot> DataList => _dataList;

    public CosmeticSlot GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CosmeticSlot Get(int key) => _dataMap[key];
    public CosmeticSlot this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

