
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// 재화 종류
/// </summary>
public partial class TbCurrency
{
    private readonly System.Collections.Generic.Dictionary<int, Currency> _dataMap;
    private readonly System.Collections.Generic.List<Currency> _dataList;
    
    public TbCurrency(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Currency>(n);
        _dataList = new System.Collections.Generic.List<Currency>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Currency _v;
            _v = global::LOP.MasterData.Currency.DeserializeCurrency(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Currency> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Currency> DataList => _dataList;

    public Currency GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Currency Get(int key) => _dataMap[key];
    public Currency this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

