
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// RankDivision(랭크 단계&#183;숨은 점수 하한&#183;감소)
/// </summary>
public partial class TbRankDivision
{
    private readonly System.Collections.Generic.Dictionary<int, RankDivision> _dataMap;
    private readonly System.Collections.Generic.List<RankDivision> _dataList;
    
    public TbRankDivision(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, RankDivision>(n);
        _dataList = new System.Collections.Generic.List<RankDivision>(n);
        for(int i = n ; i > 0 ; --i)
        {
            RankDivision _v;
            _v = global::LOP.MasterData.RankDivision.DeserializeRankDivision(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, RankDivision> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<RankDivision> DataList => _dataList;

    public RankDivision GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RankDivision Get(int key) => _dataMap[key];
    public RankDivision this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

