
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// SkinAsset
/// </summary>
public partial class TbSkinAsset
{
    private readonly System.Collections.Generic.Dictionary<string, SkinAsset> _dataMap;
    private readonly System.Collections.Generic.List<SkinAsset> _dataList;
    
    public TbSkinAsset(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, SkinAsset>(n);
        _dataList = new System.Collections.Generic.List<SkinAsset>(n);
        for(int i = n ; i > 0 ; --i)
        {
            SkinAsset _v;
            _v = global::LOP.MasterData.SkinAsset.DeserializeSkinAsset(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Code, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, SkinAsset> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<SkinAsset> DataList => _dataList;

    public SkinAsset GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SkinAsset Get(string key) => _dataMap[key];
    public SkinAsset this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

