
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace LOP.MasterData
{
/// <summary>
/// StatusEffectView
/// </summary>
public partial class TbStatusEffectView
{
    private readonly System.Collections.Generic.Dictionary<int, StatusEffectView> _dataMap;
    private readonly System.Collections.Generic.List<StatusEffectView> _dataList;
    
    public TbStatusEffectView(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, StatusEffectView>(n);
        _dataList = new System.Collections.Generic.List<StatusEffectView>(n);
        for(int i = n ; i > 0 ; --i)
        {
            StatusEffectView _v;
            _v = global::LOP.MasterData.StatusEffectView.DeserializeStatusEffectView(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, StatusEffectView> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<StatusEffectView> DataList => _dataList;

    public StatusEffectView GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public StatusEffectView Get(int key) => _dataMap[key];
    public StatusEffectView this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

